source "https://rubygems.org"

gem "jekyll"

gem "wdm", "~> 0.1.0" if Gem.win_platform?
gem "webrick"
gem "dotenv"
gem "faraday-retry"
gem "ostruct"
gem "mutex_m"
gem "just-the-docs"

group :jekyll_plugins do
  gem "github-pages"
  gem "jekyll-algolia"
  gem "jekyll-feed"
  gem "jekyll-gist"
  gem "jekyll-github-metadata"
  gem "jekyll-include-cache"
  gem "jekyll-paginate"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-default-layout"
end

